/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ir_moke_jsysbox_network_JNetwork */

#ifndef _Included_ir_moke_jsysbox_network_JNetwork
#define _Included_ir_moke_jsysbox_network_JNetwork
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     ir_moke_jsysbox_network_JNetwork
 * Method:    setIp
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ir_moke_jsysbox_network_JNetwork_setIp
  (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     ir_moke_jsysbox_network_JNetwork
 * Method:    ifUp
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ir_moke_jsysbox_network_JNetwork_ifUp
  (JNIEnv *, jclass, jstring);

/*
 * Class:     ir_moke_jsysbox_network_JNetwork
 * Method:    ifDown
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ir_moke_jsysbox_network_JNetwork_ifDown
  (JNIEnv *, jclass, jstring);

/*
 * Class:     ir_moke_jsysbox_network_JNetwork
 * Method:    updateRoute
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;IZZ)V
 */
JNIEXPORT void JNICALL Java_ir_moke_jsysbox_network_JNetwork_updateRoute
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring, jint, jboolean, jboolean);

/*
 * Class:     ir_moke_jsysbox_network_JNetwork
 * Method:    initResolve
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ir_moke_jsysbox_network_JNetwork_initResolve();

#ifdef __cplusplus
}
#endif
#endif
