/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ir_moke_jsysbox_JSystem */

#ifndef _Included_ir_moke_jsysbox_JSystem
#define _Included_ir_moke_jsysbox_JSystem
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ir_moke_jsysbox_JSystem
 * Method:    reboot
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ir_moke_jsysbox_JSystem_reboot
  (JNIEnv *, jclass);

/*
 * Class:     ir_moke_jsysbox_JSystem
 * Method:    shutdown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ir_moke_jsysbox_JSystem_shutdown
  (JNIEnv *, jclass);

/*
 * Class:     ir_moke_jsysbox_JSystem
 * Method:    mount
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_ir_moke_jsysbox_JSystem_mount
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring);

/*
 * Class:     ir_moke_jsysbox_JSystem
 * Method:    umount
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_ir_moke_jsysbox_JSystem_umount
  (JNIEnv *, jclass, jstring);

/*
 * Class:     ir_moke_jsysbox_JSystem
 * Method:    setEnv
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_ir_moke_jsysbox_JSystem_setEnv
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     ir_moke_jsysbox_JSystem
 * Method:    unSetEnv
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_ir_moke_jsysbox_JSystem_unSetEnv
  (JNIEnv *, jclass, jstring);

/*
 * Class:     ir_moke_jsysbox_JSystem
 * Method:    getEnv
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ir_moke_jsysbox_JSystem_getEnv
  (JNIEnv *, jclass, jstring);

/*
 * Class:     ir_moke_jsysbox_JSystem
 * Method:    envList
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_ir_moke_jsysbox_JSystem_envList
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
