/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ir_moke_jsysbox_system_JSystem */

#ifndef _Included_ir_moke_jsysbox_system_JSystem
#define _Included_ir_moke_jsysbox_system_JSystem
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ir_moke_jsysbox_system_JSystem
 * Method:    reboot
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ir_moke_jsysbox_system_JSystem_reboot();

/*
 * Class:     ir_moke_jsysbox_system_JSystem
 * Method:    shutdown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ir_moke_jsysbox_system_JSystem_shutdown();

/*
 * Class:     ir_moke_jsysbox_system_JSystem
 * Method:    mount
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_ir_moke_jsysbox_system_JSystem_mount
  (JNIEnv *, jclass, jstring, jstring, jstring, jint, jstring);

/*
 * Class:     ir_moke_jsysbox_system_JSystem
 * Method:    umount
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_ir_moke_jsysbox_system_JSystem_umount
  (JNIEnv *, jclass, jstring);

/*
 * Class:     ir_moke_jsysbox_system_JSystem
 * Method:    setEnv
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_ir_moke_jsysbox_system_JSystem_setEnv
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     ir_moke_jsysbox_system_JSystem
 * Method:    unSetEnv
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_ir_moke_jsysbox_system_JSystem_unSetEnv
  (JNIEnv *, jclass, jstring);

/*
 * Class:     ir_moke_jsysbox_system_JSystem
 * Method:    getEnv
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ir_moke_jsysbox_system_JSystem_getEnv
  (JNIEnv *, jclass, jstring);

/*
 * Class:     ir_moke_jsysbox_system_JSystem
 * Method:    envList
 * Signature: ()V
 */
JNIEXPORT jobject JNICALL Java_ir_moke_jsysbox_system_JSystem_envList
    (JNIEnv *, jclass);

/*
 * Class:     ir_moke_jsysbox_system_JSystem
 * Method:    setHostname
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT void JNICALL Java_ir_moke_jsysbox_system_JSystem_setHostname
    (JNIEnv *, jclass, jstring);

/*
 * Class:     ir_moke_jsysbox_system_JSystem
 * Method:    getHostname
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jstring JNICALL Java_ir_moke_jsysbox_system_JSystem_getHostname
    (JNIEnv *, jclass);



#ifdef __cplusplus
}
#endif
#endif
